export const WRONG_SERVER_DATA = 7001
export const WRONG_USER_SETTINGS_DATA = 7002
export const REQUESTING_AXIOS_DATA_PROBLEM = 7003
export const INDEX_LESS_THAN_MINIMUM = 7004

export default {
  WRONG_SERVER_DATA,
  WRONG_USER_SETTINGS_DATA,
  REQUESTING_AXIOS_DATA_PROBLEM,

  INDEX_LESS_THAN_MINIMUM
}
