export const SIGN_UP_FAILED = 1001
export const SIGN_UP_RESPONSE = 1002
export const LOG_IN_FAILED = 1003
export const LOG_IN_BAD_CREDITS = 1004
export const LOG_IN_UNEXPECTED = 1005
export const LOG_OUT_FAILED = 1006
export const LOG_OUT_UNEXPECTED = 1007

export default {
  SIGN_UP_FAILED,
  SIGN_UP_RESPONSE,
  LOG_IN_FAILED,
  LOG_IN_BAD_CREDITS,
  LOG_IN_UNEXPECTED,
  LOG_OUT_FAILED,
  LOG_OUT_UNEXPECTED
}
